### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [chanfort/BuildingBuildDetstroyAnimations#1]
Hello, under what license is this project released under ? Thank-you.

**Comment by chanfort** [comment]
My part of this repository is released under MIT License. I also added ThirdPartyNotices (https://github.com/chanfort/BuildingBuildDestroyAnimations/blob/master/ThirdPartyNotices.md) file where code examples were used from (i.e. KDTree and HeapSort algorithm).
